### ISSUE TITLE
Getting "Exception in plugin DDEV Integration"

### ISSUE THREAD

**Issue by RishiKulshreshtha** [php-perfect/ddev-intellij-plugin#161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Enter your error report ID (If available)

ff1e6a9a6030468795068270ce2a80c8

### Describe the bug

```
de.php_perfect.intellij.ddev.cmd.CommandFailedException: Failed to execute /usr/local/bin/ddev version --json-output
	at de.php_perfect.intellij.ddev.cmd.DdevImpl.execute(DdevImpl.java:42)
	at de.php_perfect.intellij.ddev.cmd.DdevImpl.version(DdevImpl.java:18)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.checkVersion(DdevStateManagerImpl.java:137)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.lambda$initialize$0(DdevStateManagerImpl.java:52)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.checkChanged(DdevStateManagerImpl.java:90)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.initialize(DdevStateManagerImpl.java:49)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.initialize(DdevStateManagerImpl.java:33)
	at de.php_perfect.intellij.ddev.InitPluginActivity.lambda$runActivity$0(InitPluginActivity.java:14)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:246)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "/usr/local/bin/ddev" (in directory "/home/rishi/Sites/RFS/jpal"): error=2, No such file or directory
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:359)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:84)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:44)
	at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:20)
	at de.php_perfect.intellij.ddev.cmd.ProcessExecutorImpl.executeCommandLine(ProcessExecutorImpl.java:16)
	at de.php_perfect.intellij.ddev.cmd.DdevImpl.execute(DdevImpl.java:30)
	... 17 more
Caused by: java.io.IOException: Cannot run program "/usr/local/bin/ddev" (in directory "/home/rishi/Sites/RFS/jpal"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:435)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:349)
	... 22 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 25 more
```

### Steps to reproduce

- Open PHPStorm as usual
- DDEV 1.0.4 is installed
- `ddev version` provides the following info:
``` 
 ITEM             VALUE                                   
 DDEV version     v1.21.5-alpha1                          
 architecture     amd64                                   
 db               drud/ddev-dbserver-mariadb-10.4:v1.21.4 
 dba              phpmyadmin:5                            
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.21.4             
 docker           23.0.1                                  
 docker-compose   v2.15.1                                 
 docker-platform  ThinkPad-E14-Gen-2                
 mutagen          0.16.0                                  
 os               linux                                   
 router           drud/ddev-router:v1.21.4                
 web              drud/ddev-webserver:20230207_fix_nvm
```

![image](https://user-images.githubusercontent.com/973783/220298878-51c47a1a-d7ef-4198-a0b2-5c0076c59771.png)

**Comment by nico-loeber** [comment]
Thank you for reporting this with all the details @RishiKulshreshtha!

The error basically says there is no ddev binary installed. But this should already be checked before the ddev version command is run (No Exception should happen):

```
Caused by: com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "/usr/local/bin/ddev" (in directory "/home/rishi/Sites/RFS/jpal"): error=2, No such file or directory
```

Could you please confirm this is the place where ddev is installed and tell if this error consists or if it occurs from time to time?

**Comment by rishi-redfinsolutions** [comment]
@nico-loeber, it appears that ddev is installed in the `/usr/bin/ddev` directory.

![image](https://user-images.githubusercontent.com/96880509/226665402-ae744087-c40a-4bb8-83d5-a8d60b1863d7.png)

**Comment by RishiKulshreshtha** [comment]
@nico-loeber, it appears that ddev is installed in the `/usr/bin/ddev` directory.

![image](https://user-images.githubusercontent.com/96880509/226665402-ae744087-c40a-4bb8-83d5-a8d60b1863d7.png)

Thank you for asking me that question, as that made me realize that this is not a `ddev-intellij-plugin` issue, but rather a config change that I should have done here.

![image](https://user-images.githubusercontent.com/973783/226683775-2070b7d6-3acc-43e7-a4ed-f13382dec4bb.png)

**Comment by rfay** [comment]
@RishiKulshreshtha the plugin automatically finds DDEV if you don't override its behavior by configuring that. I'm pretty sure you just wanted it empty.

**Comment by RishiKulshreshtha** [comment]
@rfay, you are correct. The plugin was able to detect ddev in my $PATH automatically.

![image](https://user-images.githubusercontent.com/973783/226826337-bdd9f014-2c89-4cdd-b8c1-61a4b2a97981.png)

I believe the confusion arose due to a recent upgrade that I performed on ddev. Previously, it was installed using the installation script, but I later switched to the recommended method outlined in the documentation (https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#debianubuntu).

I don't recall configuring the "DDEV Integration" path in PHPStorm. It's possible that `/usr/local/bin/ddev` was saved earlier, but after the upgrade, the "DDEV Integration" path in PHPStorm remained set to `/usr/local/bin/ddev` instead of the new and correct path `/usr/bin/ddev`. Please let me know if my understanding is correct.
