### ISSUE TITLE
Automatic PHP Configuration fails on recently set up ddev projects

### ISSUE THREAD

**Issue by calien666** [php-perfect/ddev-intellij-plugin#25]
According to https://github.com/php-perfect/ddev-intellij-plugin/discussions/21#discussioncomment-2591031 I want to report this issue.

Main setup:
* Ubuntu 2021.10 (64 bit)
* PhpStorm PS-221.5080.224
* Java 11.0.14.1+1-b2043.25 amd64 (VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.)
* set up ddev project, configured as TYPO3 v10
* composer active
* secure installation active
  * Project runs in private/, webserver runs public/
  * https://github.com/helhum/typo3-secure-web

ddev config:

```yaml
name: project
type: typo3
docroot: "public"
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames:
  - site2
  - site3
  - site4
  - site5
additional_fqdns: []
provider: default
use_dns_when_possible: true
webimage_extra_packages: [ghostscript,graphicsmagick]
composer_version: 2
timezone: Europe/Berlin
hooks:
  pre-start:
    - exec-host: cp package.json .ddev/web-build/
    - exec-host: touch .ddev/web-build/id_rsa
    - exec-host: cp ~/.ssh/id_rsa .ddev/web-build/
  post-start:
    - exec-host: ddev setup
    - composer: update
    - composer: enableext
    - exec: bash .ddev/scripts/copy-ssh.sh
    - exec-host: rm -f .ddev/web-build/id_rsa
    - exec: sudo ln -sf /tmp/node/node_modules /var/www/html/node_modules
  post-import-db:
    - exec: vendor/bin/typo3cms database:updateschema

```

Stack trace (shortened):
```
java.lang.NoClassDefFoundError: com/intellij/docker/remote/DockerComposeCredentialsType
	at de.php_perfect.intellij.ddev.php.PhpInterpreterProviderImpl.updateInterpreter(PhpInterpreterProviderImpl.java:83)
	at de.php_perfect.intellij.ddev.php.PhpInterpreterProviderImpl.registerInterpreter(PhpInterpreterProviderImpl.java:44)
	at de.php_perfect.intellij.ddev.php.ConfigurationProviderImpl.configure(ConfigurationProviderImpl.java:33)
	at de.php_perfect.intellij.ddev.php.AutoConfigurePhpInterpreterListener.onDescriptionChanged(AutoConfigurePhpInterpreterListener.java:22)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:642)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:617)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:391)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:373)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:34)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:180)
	at com.sun.proxy.$Proxy160.onDescriptionChanged(Unknown Source)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.checkChanged(DdevStateManagerImpl.java:85)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.initialize(DdevStateManagerImpl.java:33)
	at de.php_perfect.intellij.ddev.InitPluginActivity.runActivity(InitPluginActivity.java:15)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.kt:311)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:290)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration$default(StartupManagerImpl.kt:285)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1$1.run(StartupManagerImpl.kt:238)
	at com.intellij.openapi.project.DumbServiceImpl.runWithWaitForSmartModeDisabled(DumbServiceImpl.java:648)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:237)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:62)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:301)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:143)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:232)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:62)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$3$1.run(StartupManagerImpl.kt:180)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:365)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:343)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$3.run(StartupManagerImpl.kt:180)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ClassNotFoundException: com.intellij.docker.remote.DockerComposeCredentialsType PluginClassLoader(plugin=PluginDescriptor(name=DDEV Integration, id=de.php_perfect.intellij.ddev, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PhpStorm2022.1/ddev-intellij-plugin, version=1.0.0-alpha2, package=null, isBundled=false), packagePrefix=null, instanceId=124, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:215)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
```
If you need more information, please let me know.

**Comment by nico-loeber** [comment]
Thanks for reporting this possible bug!
This looks to me like the remote execution or the docker plugin is not active.
Could you please send me a list of ALL your plugins and their enabled state?

In case this error triggers a crash report, there should be a "plugins.txt" you can attach or copy here. Thanks!

**Comment by nico-loeber** [comment]
@calien666, do you have any feedback on this?

**Comment by calien666** [comment]
I checked my installed oplugins and found out, my PhpDocker integrated plugin was disabled. Since enabling it the error didn't occur anymore

**Comment by nico-loeber** [comment]
Okay, thanks for your feedback!
I will add a remark somewhere in the documentation on the additional requirements of the Docker based functionalities.

**Comment by nico-loeber** [comment]
![image](https://user-images.githubusercontent.com/18308418/164998665-db423d48-8916-42c2-8386-69f043099884.png)

This should help to identify this problem and easily fix it in the future.

**Comment by calien666** [comment]
That's fine. Glad, that I could help.
