### ISSUE TITLE
Fix `There is no ProgressIndicator or Job in this thread` errors

### ISSUE THREAD

**Issue by nico-loeber** [php-perfect/ddev-intellij-plugin#313]
Since IntelliJ 2024.1 executing commands in background triggers some error message. There is no documentation on that changed behavior. These tasks run in background and should not be cancellable and also no progress indeicator is expected.
Do we need to implement them with progress indicators? Is there some other solution?

```
2024-04-09 18:35:15,902 [  15002] SEVERE - #c.i.o.progress - There is no ProgressIndicator or Job in this thread, the current job is not cancellable.
java.lang.IllegalStateException: There is no ProgressIndicator or Job in this thread, the current job is not cancellable.
	at com.intellij.openapi.progress.CoroutinesKt$runBlockingCancellable$1.invoke(coroutines.kt:128)
	at com.intellij.openapi.progress.CoroutinesKt$runBlockingCancellable$1.invoke(coroutines.kt:126)
	at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:83)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:126)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:121)
	at com.intellij.execution.wsl.WslIjentUtil.runProcessBlocking(WslIjentUtil.kt:62)
	at com.intellij.execution.wsl.WSLDistribution.lambda$patchCommandLine$2(WSLDistribution.java:239)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:490)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:463)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:356)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:86)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:46)
	at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:20)
	at de.php_perfect.intellij.ddev.cmd.ProcessExecutorImpl.executeCommandLine(ProcessExecutorImpl.java:16)
	at de.php_perfect.intellij.ddev.cmd.DockerImpl.isRunning(DockerImpl.java:11)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.initialize(DdevStateManagerImpl.java:42)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.initialize(DdevStateManagerImpl.java:33)
	at de.php_perfect.intellij.ddev.InitPluginActivity.lambda$execute$0(InitPluginActivity.java:19)
	at com.intellij.openapi.application.impl.RwLockHolder$executeOnPooledThread$1.run(RwLockHolder.kt:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-04-09 18:35:15,939 [  15039] SEVERE - #c.i.o.progress - IntelliJ IDEA 2024.1  Build #IU-241.14494.240
2024-04-09 18:35:15,940 [  15040] SEVERE - #c.i.o.progress - JDK: 17.0.10; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-04-09 18:35:15,940 [  15040] SEVERE - #c.i.o.progress - OS: Windows 11
2024-04-09 18:35:15,941 [  15041] SEVERE - #c.i.o.progress - Plugin to blame: DDEV Integration version: 0.0.1-dev
2024-04-09 18:35:15,941 [  15041] SEVERE - #c.i.o.progress - Last Action:
```

**Comment by cleverhoods** [comment]
@nico-loeber could it be attached to https://youtrack.jetbrains.com/issue/WEB-65673/Exceptions-in-WSL-node-managers-in-empty-project?

**Comment by nico-loeber** [comment]
Requested help in the JetBrains forum: https://intellij-support.jetbrains.com/hc/en-us/community/posts/18332085482002--There-is-no-ProgressIndicator-or-Job-in-this-thread-error-in-2024-1

**Comment by Cheoooon** [comment]
What are the steps to reproduce the error? I have tried locally with the latest generated build but I only get the following error when starting the project: (PhpStorm 2024.1 PS-241.14494.237)

```java
java.io.IOException: Connection failed: too many redirects
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:660)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:366)
	at com.intellij.util.io.HttpRequests$RequestImpl.doReadBytes(HttpRequests.java:442)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:431)
	at com.intellij.util.io.RequestBuilder.lambda$readString$5(RequestBuilder.java:85)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:529)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:511)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:340)
	at com.intellij.util.io.RequestBuilder.readString(RequestBuilder.java:85)
	at de.php_perfect.intellij.ddev.version.GithubClient.loadCurrentVersion(GithubClient.java:27)
	at de.php_perfect.intellij.ddev.version.VersionCheckerImpl$1.run(VersionCheckerImpl.java:48)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:528)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:250)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:250)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:500)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

Apart from that issue, I haven't encountered any other problems while using it.

**Comment by nico-loeber** [comment]
The error does constantly happen to me, always when some command is run on terminal in background, like `ddev describe` or commands to check if docker is running.

The one you  are just reporting happend only one time to me and was not reproducible.
The plugin expects exactly one redirect from github when it requests /releases/latest to the url of the current release of ddev. In your case there was more than one redirct. If it is reproducible I would be interested to find out what is causing the second redirect.

**Comment by shochdoerfer** [comment]
Not sure if it helps, just saw that 2024.1.1 got released the other day.

**Comment by AkibaAT** [comment]
This is still an issue to me with PhpStorm 2024.2 on Windows when opening a project that's on WSL. While it is only a warning that doesn't prevent functionality, it is still annoying.
