### ISSUE TITLE
Command timed out after 8 seconds: /usr/bin/ddev describe --json-output

### ISSUE THREAD

**Issue by alex-mora** [php-perfect/ddev-intellij-plugin#362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Enter your error report ID (If available)

15350a86612d4954bec79423a0d3e5ac

### Describe the bug

I'm just using PHPSTORM IDE and suddenly the error appears. I have the last version 

de.php_perfect.intellij.ddev.cmd.CommandFailedException: Command timed out after 8 seconds: /usr/bin/ddev describe --json-output in \\wsl.localhost\Ubuntu\home\xxx\Wordpress\projectname
	at de.php_perfect.intellij.ddev.cmd.DdevImpl.execute(DdevImpl.java:70)
	at de.php_perfect.intellij.ddev.cmd.DdevImpl.describe(DdevImpl.java:39)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.checkDescription(DdevStateManagerImpl.java:155)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.checkChanged(DdevStateManagerImpl.java:90)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.updateDescription(DdevStateManagerImpl.java:74)
	at de.php_perfect.intellij.ddev.state.StateWatcherImpl.lambda$startWatching$0(StateWatcherImpl.java:34)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:275)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)

It also happens that it does not update the new port for the database, I must modify the port manually every time I start the project

### Steps to reproduce

1. Using PHPSTORM IDE and suddenly the error appears.

**Comment by AkibaAT** [comment]
The 8 seconds timeout allowed for commands to finish in is currently not configurable. That time should generally be plenty for the command to return.

The automatic configuration of the DB port depends on this command succeeding.

Is this happening every time, or randomly? What's the last line of the output when running `time ddev describe --json-output` in your project directory within WSL?

**Comment by alex-mora** [comment]
> The 8 seconds timeout allowed for commands to finish in is currently not configurable. That time should generally be plenty for the command to return.
> 
> The automatic configuration of the DB port depends on this command succeeding.
> 
**Is this happening every time, or randomly?** 
Randomly and when I open the project folder

**What's the last line of the output when running `time ddev describe --json-output` in your project directory within WSL?**

`{"level":"info","msg":"┌──────────────────────────────────┐\n│ Project: pergub ~/Sites/Laravel/ │\n│ pergub https://pergub.ddev.site  │\n│ Docker platform: docker-desktop  │\n│ Router: traefik                  │\n├─────────┬──────┬──────────┬──────┤\n│ SERVICE │ STAT │ URL/PORT │ INFO │\n├─────────┼──────┼──────────┼──────┤\n└─────────┴──────┴──────────┴──────┘\n","raw":{"approot":"/home/alex/Sites/Laravel/pergub","database_type":"mariadb","database_version":"10.4","dbimg":"ddev/ddev-dbserver-mariadb-10.4:v1.23.4","docroot":"public","fail_on_hook_fail":false,"hostname":"pergub.ddev.site","hostnames":["pergub.ddev.site"],"httpURLs":["http://pergub.ddev.site","http://127.0.0.1:52194"],"httpsURLs":["https://pergub.ddev.site","https://127.0.0.1:52195"],"httpsurl":"https://pergub.ddev.site","httpurl":"http://pergub.ddev.site","mailpit_https_url":"https://pergub.ddev.site:8026","mailpit_url":"http://pergub.ddev.site:8025","mutagen_enabled":false,"name":"pergub","nodejs_version":"20","performance_mode":"none","php_version":"8.2","primary_url":"https://pergub.ddev.site","router":"traefik","router_disabled":false,"router_http_port":"80","router_https_port":"443","router_status":"stopped","router_status_log":"","services":{"web":{"exposed_ports":"443,80,8025","full_name":"ddev-pergub-web","host_http_url":"http://127.0.0.1:52194","host_https_url":"https://127.0.0.1:52195","host_ports":"52195,52194","http_url":"http://pergub.ddev.site","https_url":"https://pergub.ddev.site","image":"ddev/ddev-webserver:v1.23.4","short_name":"web","status":"running","virtual_host":"pergub.ddev.site"}},"shortroot":"~/Sites/Laravel/pergub","ssh_agent_status":"exited","status":"unhealthy","status_desc":"db: stopped\n","type":"laravel","urls":["https://pergub.ddev.site","https://127.0.0.1:52195","http://pergub.ddev.site","http://127.0.0.1:52194"],"webimg":"ddev/ddev-webserver:v1.23.4","webserver_type":"nginx-fpm","xdebug_enabled":false},"time":"2024-08-29T10:43:53-05:00"} `

**Comment by alex-mora** [comment]
I changed the ddev binary path in DDEV Integration, and everything works fine. I updated to the latest version of ddev and the binary path changed. I'm closing this issue because it seems to be a configuration problem in the project.
