### ISSUE TITLE
Incompatible with ddev v1.23.5

### ISSUE THREAD

**Issue by xHeaven** [php-perfect/ddev-intellij-plugin#380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Enter your error report ID (If available)

0377667ef3e74dfcb1ec3a2672470099

### Describe the bug

The DDEV Integration plugin is currently incompatible with DDEV 1.23.5

### Steps to reproduce

1. Update DDEV to 1.23.5
2. Try to use DDEV Integration 1.2.4

### Additional context

PHPStorm stacktrace

```
de.php_perfect.intellij.ddev.cmd.CommandFailedException: Command '/usr/bin/ddev describe --json-output' returned non zero exit code {exitCode=1, timeout=false, cancelled=false, stdout=, stderr={"level":"fatal","msg":"\u001b[31mFailed to describe project(s): the vacation-tracker project has an unsupported database type/version: 'postgres:17', DDEV amd64 only supports the following database types and versions: mariadb: [5.5 10.0 10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.11 11.4], mysql: [5.5 5.6 5.7 8.0], postgres: [9 10 11 12 13 14 15 16]\u001b[0m","time":"2024-10-21T22:18:41+02:00"}
}
	at de.php_perfect.intellij.ddev.cmd.DdevImpl.execute(DdevImpl.java:74)
	at de.php_perfect.intellij.ddev.cmd.DdevImpl.describe(DdevImpl.java:39)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.checkDescription(DdevStateManagerImpl.java:155)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.lambda$initialize$0(DdevStateManagerImpl.java:54)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.checkChanged(DdevStateManagerImpl.java:90)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.initialize(DdevStateManagerImpl.java:49)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.initialize(DdevStateManagerImpl.java:33)
	at de.php_perfect.intellij.ddev.InitPluginActivity.lambda$execute$0(InitPluginActivity.java:19)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport$executeOnPooledThread$1.run(AnyThreadWriteThreadingSupport.kt:134)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

Other errors and warnings:
```
DDEV integration entered unknown state
The DDEV Integration Plugin has lost track of the DDEV status. This most likely occurs together with another related error message. Please report this issue if it occurs repeatedly.
```

```
DDEV update available
Your DDEV version v1.23.4 is outdated. Update to v1.23.5 now.
```

**Comment by AkibaAT** [comment]
This seems to me like /usr/bin/ddev, which the IntelliJ plugin is configured to use, is still version 1.23.4. The error message in your report is from DDEV itself: "unsupported database type/version: 'postgres:17'"
postgres 17 support was added in 1.23.5.

Please verify the version by running `/usr/bin/ddev version`.

**Comment by xHeaven** [comment]
> This seems to me like /usr/bin/ddev, which the IntelliJ plugin is configured to use, is still version 1.23.4. The error message in your report is from DDEV itself: "unsupported database type/version: 'postgres:17'" postgres 17 support was added in 1.23.5.
> 
> Please verify the version by running `/usr/bin/ddev version`.

Oh dang, it was indeed on my side. Thanks for the clarification, issue solved.
