### ISSUE TITLE
"Failed to parse output of wsl..." when debug mode is enabled

### ISSUE THREAD

**Issue by rfay** [php-perfect/ddev-intellij-plugin#39]
I installed alpha3 on Windows with PhpStorm 2022.1 and opened a WSL2 project and things went bad before I could even do anything:

```
de.php_perfect.intellij.ddev.cmd.CommandFailedException: Failed to parse output of command 'C:\Windows\system32\wsl.exe --distribution Ubuntu --exec /bin/bash -l -c "export DDEV_NONINTERACTIVE=true && ddev describe --json-output"': {"level":"debug","msg":"detected terminal width=80 urlPortWidth=32 infoWidth=20","time":"2022-05-09T18:29:02-06:00"}
{"level":"info","msg":"┌─────────────────────────────────────────────────────────────────────────────┐\n│ Project: d9 ~/workspace/d9 https://d9.ddev.site                             │\n│ Docker environment: docker 20.10.14                                         │\n├────────────┬──────┬────────────────────────────────────┬────────────────────┤\n│ SERVICE    │ STAT │ URL/PORT                           │ INFO               │\n├────────────┼──────┼────────────────────────────────────┼────────────────────┤\n│ web        │ \u001b[32mOK\u001b[0m   │ https://d9.ddev.site               │ drupal9 PHP7.4     │\n│            │      │ InDocker: ddev-d9-web:443,80,8025  │ nginx-fpm          │\n│            │      │ Host: localhost:61301,61302        │ docroot:'web'      │\n│            │      │                                    │ NodeJS:16          │\n├────────────┼──────┼────────────────────────────────────┼────────────────────┤\n│ db         │ \u001b[32mOK\u001b[0m   │ InDocker: ddev-d9-db:3306          │ mysql:8.0          │\n│            │      │ Host: localhost:52319              │ User/Pass: 'db/db' │\n│            │      │                                    │ or 'root/root'     │\n├────────────┼──────┼────────────────────────────────────┼────────────────────┤\n│ PHPMyAdmin │ \u001b[32mOK\u001b[0m   │ https://d9.ddev.site:8037          │                    │\n│            │      │ InDocker: ddev-d9-dba:80           │                    │\n│            │      │ `ddev launch -p`                   │                    │\n├────────────┼──────┼────────────────────────────────────┼────────────────────┤\n│ Mailhog    │      │ MailHog: https://d9.ddev.site:8026 │                    │\n│            │      │ `ddev launch -m`                   │                    │\n├────────────┼──────┼────────────────────────────────────┼────────────────────┤\n│ All URLs   │      │ https://d9.ddev.site,              │                    │\n│            │      │ https://127.0.0.1:61301,           │                    │\n│            │      │ http://d9.ddev.site,               │                    │\n│            │      │ http://127.0.0.1:61302             │                    │\n└────────────┴──────┴────────────────────────────────────┴────────────────────┘\n","raw":{"approot":"/home/rfay/workspace/d9","database_type":"mysql","database_version":"8.0","dbimg":"drud/ddev-dbserver-mysql-8.0:v1.19.2","dbinfo":{"database_type":"mysql","database_version":"8.0","dbPort":"3306","dbname":"db","host":"db","password":"db","published_port":52319,"username":"db"},"docroot":"web","fail_on_hook_fail":false,"hostname":"d9.ddev.site","hostnames":["d9.ddev.site"],"httpURLs":["http://d9.ddev.site","http://127.0.0.1:61302"],"httpsURLs":["https://d9.ddev.site","https://127.0.0.1:61301"],"httpsurl":"https://d9.ddev.site","httpurl":"http://d9.ddev.site","mailhog_https_url":"https://d9.ddev.site:8026","mailhog_url":"http://d9.ddev.site:8025","mutagen_enabled":false,"name":"d9","nfs_mount_enabled":false,"nodejs_version":"16","php_version":"7.4","phpmyadmin_https_url":"https://d9.ddev.site:8037","phpmyadmin_url":"http://d9.ddev.site:8036","primary_url":"https://d9.ddev.site","router_disabled":false,"router_http_port":"80","router_https_port":"443","router_status":"healthy","router_status_log":"container was previously healthy, so sleeping 59 seconds before continuing healthcheck...  nginx config valid:OK  ddev nginx config:generated nginx healthcheck endpoint:OK ddev-router is healthy with 3 upstreams","services":{"db":{"exposed_ports":"3306","full_name":"ddev-d9-db","host_ports":"52319","image":"drud/ddev-dbserver-mysql-8.0:v1.19.2","status":"running"},"dba":{"exposed_ports":"80","full_name":"ddev-d9-dba","host_ports":"","http_url":"http://d9.ddev.site:8036","https_url":"https://d9.ddev.site:8037","image":"phpmyadmin:5","status":"running"},"web":{"exposed_ports":"443,80,8025","full_name":"ddev-d9-web","host_http_url":"http://127.0.0.1:61302","host_https_url":"https://127.0.0.1:61301","host_ports":"61301,61302","http_url":"http://d9.ddev.site","https_url":"https://d9.ddev.site","image":"drud/ddev-webserver:v1.19.2","status":"running"}},"shortroot":"~/workspace/d9","ssh_agent_status":"healthy","status":"running","type":"drupal9","urls":["https://d9.ddev.site","https://127.0.0.1:61301","http://d9.ddev.site","http://127.0.0.1:61302"],"webimg":"drud/ddev-webserver:v1.19.2","webserver_type":"nginx-fpm","xdebug_enabled":false},"time":"2022-05-09T18:29:02-06:00"}

	at de.php_perfect.intellij.ddev.cmd.DdevImpl.execute(DdevImpl.java:70)
	at de.php_perfect.intellij.ddev.cmd.DdevImpl.describe(DdevImpl.java:47)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.checkDescription(DdevStateManagerImpl.java:129)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.lambda$initialize$0(DdevStateManagerImpl.java:37)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.checkChanged(DdevStateManagerImpl.java:78)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.initialize(DdevStateManagerImpl.java:33)
	at de.php_perfect.intellij.ddev.InitPluginActivity.runActivity(InitPluginActivity.java:15)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.kt:311)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:290)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration$default(StartupManagerImpl.kt:285)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1$1.run(StartupManagerImpl.kt:238)
	at com.intellij.openapi.project.DumbServiceImpl.runWithWaitForSmartModeDisabled(DumbServiceImpl.java:648)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:237)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:62)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:301)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:143)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:232)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:62)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$3$1.run(StartupManagerImpl.kt:180)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:365)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:343)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$3.run(StartupManagerImpl.kt:180)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool.awaitQuiescence(ForkJoinPool.java:2984)
	at com.intellij.idea.StartupUtil.start(StartupUtil.java:270)
	at com.intellij.idea.Main.bootstrap(Main.java:118)
	at com.intellij.idea.Main.main(Main.java:79)
Caused by: de.php_perfect.intellij.ddev.cmd.parser.JsonParserException: Encountered invalid JSON '{"level":"debug","msg":"detected terminal width=80 urlPortWidth=32 infoWidth=20","time":"2022-05-09T18:29:02-06:00"}
{"level":"info","msg":"┌─────────────────────────────────────────────────────────────────────────────┐\n│ Project: d9 ~/workspace/d9 https://d9.ddev.site                             │\n│ Docker environment: docker 20.10.14                                         │\n├────────────┬──────┬────────────────────────────────────┬────────────────────┤\n│ SERVICE    │ STAT │ URL/PORT                           │ INFO               │\n├────────────┼──────┼────────────────────────────────────┼────────────────────┤\n│ web        │ \u001b[32mOK\u001b[0m   │ https://d9.ddev.site               │ drupal9 PHP7.4     │\n│            │      │ InDocker: ddev-d9-web:443,80,8025  │ nginx-fpm          │\n│            │      │ Host: localhost:61301,61302        │ docroot:'web'      │\n│            │      │                                    │ NodeJS:16          │\n├────────────┼──────┼────────────────────────────────────┼────────────────────┤\n│ db         │ \u001b[32mOK\u001b[0m   │ InDocker: ddev-d9-db:3306          │ mysql:8.0          │\n│            │      │ Host: localhost:52319              │ User/Pass: 'db/db' │\n│            │      │                                    │ or 'root/root'     │\n├────────────┼──────┼────────────────────────────────────┼────────────────────┤\n│ PHPMyAdmin │ \u001b[32mOK\u001b[0m   │ https://d9.ddev.site:8037          │                    │\n│            │      │ InDocker: ddev-d9-dba:80           │                    │\n│            │      │ `ddev launch -p`                   │                    │\n├────────────┼──────┼────────────────────────────────────┼────────────────────┤\n│ Mailhog    │      │ MailHog: https://d9.ddev.site:8026 │                    │\n│            │      │ `ddev launch -m`                   │                    │\n├────────────┼──────┼────────────────────────────────────┼────────────────────┤\n│ All URLs   │      │ https://d9.ddev.site,              │                    │\n│            │      │ https://127.0.0.1:61301,           │                    │\n│            │      │ http://d9.ddev.site,               │                    │\n│            │      │ http://127.0.0.1:61302             │                    │\n└────────────┴──────┴────────────────────────────────────┴────────────────────┘\n","raw":{"approot":"/home/rfay/workspace/d9","database_type":"mysql","database_version":"8.0","dbimg":"drud/ddev-dbserver-mysql-8.0:v1.19.2","dbinfo":{"database_type":"mysql","database_version":"8.0","dbPort":"3306","dbname":"db","host":"db","password":"db","published_port":52319,"username":"db"},"docroot":"web","fail_on_hook_fail":false,"hostname":"d9.ddev.site","hostnames":["d9.ddev.site"],"httpURLs":["http://d9.ddev.site","http://127.0.0.1:61302"],"httpsURLs":["https://d9.ddev.site","https://127.0.0.1:61301"],"httpsurl":"https://d9.ddev.site","httpurl":"http://d9.ddev.site","mailhog_https_url":"https://d9.ddev.site:8026","mailhog_url":"http://d9.ddev.site:8025","mutagen_enabled":false,"name":"d9","nfs_mount_enabled":false,"nodejs_version":"16","php_version":"7.4","phpmyadmin_https_url":"https://d9.ddev.site:8037","phpmyadmin_url":"http://d9.ddev.site:8036","primary_url":"https://d9.ddev.site","router_disabled":false,"router_http_port":"80","router_https_port":"443","router_status":"healthy","router_status_log":"container was previously healthy, so sleeping 59 seconds before continuing healthcheck...  nginx config valid:OK  ddev nginx config:generated nginx healthcheck endpoint:OK ddev-router is healthy with 3 upstreams","services":{"db":{"exposed_ports":"3306","full_name":"ddev-d9-db","host_ports":"52319","image":"drud/ddev-dbserver-mysql-8.0:v1.19.2","status":"running"},"dba":{"exposed_ports":"80","full_name":"ddev-d9-dba","host_ports":"","http_url":"http://d9.ddev.site:8036","https_url":"https://d9.ddev.site:8037","image":"phpmyadmin:5","status":"running"},"web":{"exposed_ports":"443,80,8025","full_name":"ddev-d9-web","host_http_url":"http://127.0.0.1:61302","host_https_url":"https://127.0.0.1:61301","host_ports":"61301,61302","http_url":"http://d9.ddev.site","https_url":"https://d9.ddev.site","image":"drud/ddev-webserver:v1.19.2","status":"running"}},"shortroot":"~/workspace/d9","ssh_agent_status":"healthy","status":"running","type":"drupal9","urls":["https://d9.ddev.site","https://127.0.0.1:61301","http://d9.ddev.site","http://127.0.0.1:61302"],"webimg":"drud/ddev-webserver:v1.19.2","webserver_type":"nginx-fpm","xdebug_enabled":false},"time":"2022-05-09T18:29:02-06:00"}
'
	at de.php_perfect.intellij.ddev.cmd.parser.JsonParser.parseJson(JsonParser.java:42)
	at de.php_perfect.intellij.ddev.cmd.parser.JsonParser.parse(JsonParser.java:19)
	at de.php_perfect.intellij.ddev.cmd.DdevImpl.execute(DdevImpl.java:66)
	... 34 more
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
	at com.google.gson.Gson.assertFullConsumption(Gson.java:967)
	at com.google.gson.Gson.fromJson(Gson.java:957)
	at com.google.gson.Gson.fromJson(Gson.java:905)
	at de.php_perfect.intellij.ddev.cmd.parser.JsonParser.parseJson(JsonParser.java:40)
	... 36 more
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1597)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1404)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at com.google.gson.Gson.assertFullConsumption(Gson.java:963)
	... 39 more
```

**Comment by rfay** [comment]
I did use the PhpStorm facility to report this.

**Comment by nico-loeber** [comment]
Thanks for reporting this. I will try to reproduce and fix this asap!

> I tried to use the PhpStorm facility to report, but the "Report and clear all" was greyed out.

Yes, we need to provide a backend that can handle those error reports first https://github.com/php-perfect/ddev-intellij-plugin/issues/37.

**Comment by nico-loeber** [comment]
After reading your error carefully I think I know at least what is causing the error:
ddev describe -j is expected to return ONE json object containing the information.
In your case it returns two objects.

first one:
```json
{"level":"debug","msg":"detected terminal width=80 urlPortWidth=32 infoWidth=20","time":"2022-05-09T18:29:02-06:00"}
```

2nd one
```json
{"level":"info","msg":"┌────────────────── " ... }
```

The first one is not expected and makes the output invald as IF there are multiple objects to parse they would need to be within [ ] to get parsed as a list.

Do you maybe know what is causing the 1st output for you? I'm currently not able to reproduce this with my ddev version 1.19.1, @rfay.

**Comment by nico-loeber** [comment]
Please note, we already had the same issue with the SegmentKey warning.
https://github.com/drud/ddev/pull/3574

**Comment by rfay** [comment]
I know what it is, `export DDEV_DEBUG=true`. :)

**Comment by rfay** [comment]
Maybe you should only use the first object?

**Comment by nico-loeber** [comment]
The first one would be the debug message in this case.
Also there is no "first object" at all, because the output is no valid json. So there is no way to deserialize it without an error.

I still hope for a `--api` mode or something similar in ddev that disables logging output to the console and returns only the output of `app.Describe(false)` (desc return value) without any further rendering.
This would increase stability as well as performance and would allow me to delete some unnecessary plugin code.

**Comment by rfay** [comment]
Probably needs to be fixed to be valid json.

**Comment by rfay** [comment]
Easy fix for this that fixes existing ddev is to just `unset DDEV_DEBUG` in the environment where you launch ddev. I'll return to it also with DDEV_DEBUG off.

**Comment by nico-loeber** [comment]
Yes but the goal would be to make the plugin work with ddev in debug mode as well. 
maybe you want to debug something related to the interoperation with the integration plugin or something like that.

As I already suggested a stable api would solve this but I have too many open topics right now to care about this right now.
I hope you can continue testing, without debug enabled.

**Comment by rfay** [comment]
I will certainly continue again without debug enabled, but since DDEV_DEBUG is not even not even exposed in the user-oriented docs, and since it would (never?) be useful in the context of the plugin, I don't see any harm in the plugin unsetting the env var.

**Comment by nico-loeber** [comment]
Yes you are right. For this specific case it would be enough to filter out this environment variable.
But first of all, this would add code to the plugin to avoid invalid output of ddev. 
Any kind of additionally logged output to the console will interupt the communication between ddev and the plugin.
We already had this in https://github.com/drud/ddev/pull/3574.

I am quite sure there might be several more situations when an additional log message of any level may occur in the `--json` output.
I am striving for a future proof solution to this kind of issue. Not in the short term, but in the medium term.

**Comment by rfay** [comment]
You are ambitious and amazing.
