### ISSUE TITLE
Failed to parse output of `ddev version --json-output`

### ISSUE THREAD

**Issue by jonaseberle** [php-perfect/ddev-intellij-plugin#56]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [ ] I am sure

### Describe the bug

After changing ddev-versions, PhpStorm reported an error:

```
de.php_perfect.intellij.ddev.cmd.CommandFailedException: Failed to parse output of command 'ddev version --json-output': 

...

	at de.php_perfect.intellij.ddev.cmd.DdevImpl.execute(DdevImpl.java:70)
	at de.php_perfect.intellij.ddev.cmd.DdevImpl.version(DdevImpl.java:43)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.checkVersion(DdevStateManagerImpl.java:112)
```

This seems to be a problem with `ddev --json-output` which includes the "chore" work (in this case updating the internal docker-compose) in its `--json-output`.

```
$ ddev version --json-output
{
    "level": "info",
    "msg": "Downloading https://github.com/docker/compose/releases/download/v2.5.1/docker-compose-linux-x86_64 ...",
    "time": "2022-05-22T12:42:34+02:00"
}
docker-compose 25.30 MiB / 25.30 MiB [=======================================================================================================] 100.00% 5s
{
    "level": "info",
    "msg": "Download complete.",
    "time": "2022-05-22T12:42:40+02:00"
}
{
    "level": "info",
    "msg": " ITEM             VALUE                                   \n DDEV version     v1.19.2-23-gd8a338ba                    \n architecture     amd64                                   \n db               drud/ddev-dbserver-mariadb-10.3:v1.19.2 \n dba              phpmyadmin:5                            \n ddev-ssh-agent   drud/ddev-ssh-agent:v1.19.0             \n docker           20.10.15                                \n docker-compose   v2.5.1                                  \n docker-platform  e480                                    \n mutagen          0.14.0                                  \n os               linux                                   \n router           drud/ddev-router:v1.19.0                \n web              drud/ddev-webserver:v1.19.2             \n",
    "raw": {
        "DDEV version": "v1.19.2-23-gd8a338ba",
        "architecture": "amd64",
        "build info": "BUILDINFO should have new info",
        "db": "drud/ddev-dbserver-mariadb-10.3:v1.19.2",
        "dba": "phpmyadmin:5",
        "ddev-ssh-agent": "drud/ddev-ssh-agent:v1.19.0",
        "docker": "20.10.15",
        "docker-compose": "v2.5.1",
        "docker-platform": "e480",
        "mutagen": "0.14.0",
        "os": "linux",
        "router": "drud/ddev-router:v1.19.0",
        "web": "drud/ddev-webserver:v1.19.2"
    },
    "time": "2022-05-22T12:42:40+02:00"
}
```

### Steps to reproduce

1. checkout DDEV 1.19.2 and [build it](https://ddev.readthedocs.io/en/latest/developers/building-contributing/#building)
2. make sure it is your default `ddev`, e.g. by putting it into your `$PATH` or symlinking it from something already there (e.g. `$HOME/bin`)
3. Run any ddev command, e.g. `ddev version --json-output`
4. checkout current main (d8a338baac12e9747aac22c60e7f4b480464f0b0) and build it
5. Run any ddev command, e.g. `ddev version --json-output`

### Additional context

I don't know if this behaviour could be changed in DDEV.

For the time being, a second call to `ddev version --json-output` would have delivered the expected JSON.

**Comment by nico-loeber** [comment]
I just stumbled across this myself and was going to create an issue for it when I saw yours!
Thanks for reporting!

As you may have seen, there were/are several problems related to unexpected output of `ddev describe --j`. I will try to find a more reliable solution in consultation with @rfay.

```text
de.php_perfect.intellij.ddev.cmd.CommandFailedException: Failed to parse output of command 'C:\Windows\system32\wsl.exe --distribution Ubuntu --exec /bin/bash -l -c "export DDEV_NONINTERACTIVE=true && ddev version --json-output"': {"level":"info","msg":"Downloading https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-linux-x86_64 ...","time":"2022-05-22T15:35:49+02:00"}
{"level":"info","msg":"Download complete.","time":"2022-05-22T15:35:51+02:00"}
{"level":"info","msg":" ITEM             VALUE                                   \n DDEV version     v1.19.0-rc1                             \n architecture     amd64                                   \n db               drud/ddev-dbserver-mariadb-10.3:v1.19.0 \n dba              phpmyadmin:5                            \n ddev-ssh-agent   drud/ddev-ssh-agent:v1.19.0             \n docker           20.10.14                                \n docker-compose   v2.2.2                                  \n docker-platform  docker-desktop                          \n mutagen          0.12.0                                  \n os               linux                                   \n router           drud/ddev-router:v1.19.0                \n web              drud/ddev-webserver:v1.19.0-rc1         \n","raw":{"DDEV version":"v1.19.0-rc1","architecture":"amd64","build info":"BUILDINFO should have new info","db":"drud/ddev-dbserver-mariadb-10.3:v1.19.0","dba":"phpmyadmin:5","ddev-ssh-agent":"drud/ddev-ssh-agent:v1.19.0","docker":"20.10.14","docker-compose":"v2.2.2","docker-platform":"docker-desktop","mutagen":"0.12.0","os":"linux","router":"drud/ddev-router:v1.19.0","web":"drud/ddev-webserver:v1.19.0-rc1"},"time":"2022-05-22T15:35:51+02:00"}
```

Related:
https://github.com/php-perfect/ddev-intellij-plugin/issues/39
https://github.com/drud/ddev/pull/3574

**Comment by rfay** [comment]
DDEV fixes this in 
* https://github.com/drud/ddev/pull/3860, but it's important for the plugin to be a bit more resilient to externally generated input, for many reasons including security and robustness.
