### ISSUE TITLE
 ID 'DdevIntegration.Services.ddev-config-test-mailhog' is already taken by action 'Open Mailhog (Open ddev-config-test-mailhog service in your browser)'

### ISSUE THREAD

**Issue by jonaseberle** [php-perfect/ddev-intellij-plugin#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Describe the bug

When opening several DDEV-projects (can happen with 2; always reproducible with 3), an error is shown:

```
com.intellij.diagnostic.PluginException: ID 'DdevIntegration.Services.ddev-config-test-mailhog' is already taken by action 'Open Mailhog (Open ddev-config-test-mailhog service in your browser)' (class de.php_perfect.intellij.ddev.actions.OpenServiceAction). ID 'DdevIntegration.Services.ddev-config-test-mailhog' cannot be registered for the same action (module=PluginDescriptor(name=DDEV Integration, id=de.php_perfect.intellij.ddev, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PhpStorm2022.1/ddev-intellij-plugin, version=1.0.0-alpha3, package=null, isBundled=false))
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:351)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:347)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.java:1276)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.java:1251)
	at de.php_perfect.intellij.ddev.serviceActions.ServiceActionManagerImpl.lambda$updateActionsByDescription$1(ServiceActionManagerImpl.java:72)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1505)
	at de.php_perfect.intellij.ddev.serviceActions.ServiceActionManagerImpl.updateActionsByDescription(ServiceActionManagerImpl.java:72)
	at de.php_perfect.intellij.ddev.serviceActions.ServiceActionChangedListener.onDescriptionChanged(ServiceActionChangedListener.java:18)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:642)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:617)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:391)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:373)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:34)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:180)
	at com.sun.proxy.$Proxy169.onDescriptionChanged(Unknown Source)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.checkChanged(DdevStateManagerImpl.java:85)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.initialize(DdevStateManagerImpl.java:33)
	at de.php_perfect.intellij.ddev.InitPluginActivity.runActivity(InitPluginActivity.java:15)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.kt:311)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:290)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration$default(StartupManagerImpl.kt:285)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1$1.run(StartupManagerImpl.kt:238)
	at com.intellij.openapi.project.DumbServiceImpl.runWithWaitForSmartModeDisabled(DumbServiceImpl.java:648)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:237)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:62)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:301)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:143)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:232)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:62)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$3$1.run(StartupManagerImpl.kt:180)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:365)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:343)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$3.run(StartupManagerImpl.kt:180)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

### Steps to reproduce

1. Open a DDEV project
2. Open another DDEV project (new window)
3. Open another DDEV project (new window)

### Additional context

PhpStorm 2022.1.1

**Comment by nico-loeber** [comment]
Hi @jonaseberle, 
this should already be fixed in the master branch. It's the same issue as https://github.com/php-perfect/ddev-intellij-plugin/issues/52.

If you are brave you can test directly on the master branch by downloading the latest build from the pipeline:
https://github.com/php-perfect/ddev-intellij-plugin/actions/runs/2366779281 (The zip to install the plugin is listed in the artifacts).

I will close this as a duplicate. Thanks anyway for reporting!
